### ISSUE TITLE
colloquy.info has ipv6 but push notifications are not accepted on it

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3646] opened 2017-08-09 01:57 UTC
*Issue migrated from trac ticket [#9114](http://colloquy.info/project/ticket/9114)*

**type:** Defect | **component:** Colloquy (Bouncer) | **severity:** Normal | **version:** 1.8 (iOS) | **status:** new
___
#### 2017-08-09 01:57:57: Sam <sam@… created the issue

When ipv6 is enabled, push does not work from znc.  It tries to connect to 2605:de00:1:1:4a:61:0:11f on port 7906 but the connection is refused.  When I force it to use ipv4 to 207.38.93.199 it works fine.

```
13:51:40.437201 IP6 2001:x:x:x::x.37013 > 2605:de00:1:1:4a:61:0:11f.7906: Flags [S], seq 2795446325, win 28800, options [mss 1440,sackOK,TS val 1287524442 ecr 0,nop,wscale 7], length 0
13:51:40.505679 IP6 2605:de00:1:1:4a:61:0:11f > 2001:x:x:x::x: ICMP6, destination unreachable, unreachable port, 2605:de00:1:1:4a:61:0:11f tcp port 7906, length 88
```

**Comment by zadr** [comment] 2017-11-13 06:59
Dupe of https://github.com/colloquy/colloquy/issues/3633

**Closed by zadr** 2017-11-13 06:59 UTC
Labels: Affected: iOS 1.8, Component: Bouncer, Component: ChatCore, Impact: Medium, Type: Bug
