### ISSUE TITLE
Loss of lock-to-bottom function with OS Maverick update

### ISSUE THREAD

**Issue by datan00b** [colloquy/colloquy#3698] opened 2020-03-15 20:57 UTC
As the the title states, I think the upgrade messed with something because the chat window no longer locks to the bottom/newest message.

**Comment by akempgen** [comment] 2020-03-16 19:30
Duplicate of #3691. The build at http://alex.speanet.info/stuff/Colloquy_7048_with_Bouncer_103.zip contains a fix for this issue.

**Closed by akempgen** 2020-03-16 19:30 UTC
